SUBJECT:Attention replace_last_name you have an urgent message from replace_which_connections.
We have found that you have duplicate profiles.  Each of your duplicate profiles will receive an email indicating the user name of the suspected duplicate.  This mail addresses...

User Name:	replace_user_name

replace_which_connections does not allow duplicate profiles.  We ask that you email us at replace_admin_email and tell us which profile(s) you would like us to delete.  If we do not hear from you shortly the following profile will be deleted without further warning:

User Name:	replace_user_name

Thank you,

replace_which_connections
replace_html_root