SUBJECT:Hello replace_last_name

It has come to the attention of replace_which_connections that many of or our members, who reside outside of the United States, do not have the ability to pay for Premium membership using a credit card.

replace_which_connections has decided to extend an International promotional membership to all members outside of the United States to give us a chance to provide alternative payment methods that are more suitable to our international clientele.

User Name:	replace_user_name
Password:	replace_password

Please log in to replace_html_root and enjoy the full functionality of your new International membership for 15 days.  And don't forget to pick one of the payment options for your Premium membership so as not to interrupt your access to replace_which_connections once your promotion expires.

Thank you,

replace_which_connections
replace_admin_email
