#!/usr/local/bin/perl -w

use MSSQL::DBlib;
use MSSQL::DBlib::Const::General;
use MSSQL::DBlib::Const::Datatypes;

use CGI qw/:standard/;
use strict;

# Add directories to perl environment path...
# Smithers
unshift @INC, "D:/Required/INC/";
# Grimes
unshift @INC, "C:/Required/INC/";

require "DatabaseFunctions.pl";
require "CgiFunctions.pl";
require "UtilityFunctions.pl";

my $DebugThisAp			   = "0";
my $DebugCgiFunctions 	   = "0";
my $DebugDatabaseFunctions = "0";
my $DebugUtilityFunctions  = "0";

my $ProgramName = "AuthorizeNetReceive.cgi";

#Begin HTML so errors show up in browser...
print CGI::header('text/html');
print "<HTML>\n";

# Determine what libraries to use base on the execution dir...
my $CurrentFilePath = __FILE__;
# Initialize LinkMap Hash variable "Map"...
my %Map = &UtilityFunctions::Load_LinkMap($CurrentFilePath, 1); 

# Severe Error:  No LinkMap.dat file found -- EXIT --
if($Map{'CONFIG'} eq 'ERROR')
	{
		&UtilityFunctions::Print_Error("LinkMap Error.<BR><BR>Contact Site Administrator.", $DebugUtilityFunctions, %Map);
	}
else
	{
		print "<!-- $Map{'CONFIG'} -->\n";
		$Map{'PROGRAM_NAME'} = $ProgramName;
	}

my @QueryStringParams;
my %QueryStringHash;

# Load the values passed in into the QueryStringHash...
@QueryStringParams = CGI::param();
%QueryStringHash = &CgiFunctions::Load_Query_String_Hash(\@QueryStringParams, \$DebugCgiFunctions);

my $transaction_id			= $QueryStringHash{'x_ship_to_address'};
my $user_name				= $QueryStringHash{'x_ship_to_first_name'};
my $months_joined			= $QueryStringHash{'x_ship_to_city'};
my $card_type				= $QueryStringHash{'x_ship_to_state'};
my $last_four				= $QueryStringHash{'x_ship_to_zip'};
my $transaction_type		= $QueryStringHash{'x_type'};
my $x_response_code			= $QueryStringHash{'x_response_code'};
my $x_cvv2_resp_code		= $QueryStringHash{'x_cvv2_resp_code'};
my $amount					= $QueryStringHash{'x_amount'};
my $name_on_card			= $QueryStringHash{'x_ship_to_last_name'};
my $x_response_subcode		= $QueryStringHash{'x_response_subcode'};
my $x_response_reason_code	= $QueryStringHash{'x_response_reason_code'};
my $x_response_reason_text	= $QueryStringHash{'x_response_reason_text'};
my $x_auth_code				= $QueryStringHash{'x_auth_code'};
my $x_avs_code				= $QueryStringHash{'x_avs_code'};
# x_trans_id generated by Authorize Net for use when sending CREDIT
my $x_trans_id				= $QueryStringHash{'x_trans_id'};
my $x_md5_hash				= $QueryStringHash{'x_md5_hash'};
my $x_description			= $QueryStringHash{'x_description'};


if($card_type eq "0")
	{
		$card_type = "Unnecessary";
	}
if($card_type eq "4")
	{
		$card_type = "Visa";
	}
elsif($card_type eq "5")
	{
		$card_type = "Master Card";
	}
else
	{
	 	print "<!-- Unknown card type ($card_type) -->\n";
		$card_type = "Unknown";
	}


my $affiliate_tracking_id	= "";
my $plan_unique_id			= "";
my $transaction_amount		= "";

# Initialize the sql statement and build it as you go...												   														  
my $SqlStatement = "transaction_credit_card_receive \"$transaction_id\", \"$x_response_code\", \"$x_cvv2_resp_code\", \"$x_response_subcode\", \"$x_response_reason_code\", \"$x_response_reason_text\", \"$x_auth_code\", \"$x_avs_code\", \"$x_trans_id\", \"$x_md5_hash\"";

my $status = $MSSQL::DBlib::dbh = MSSQL::DBlib->dblogin($Map{'DBUSER'}, $Map{'DBPWD'}, $Map{'DBNAME'}, "$ProgramName");
$status = $MSSQL::DBlib::dbh->dbcmd($SqlStatement);
$status = $MSSQL::DBlib::dbh->dbsqlexec();
##########################
# Get ONLY result set...
##########################
# dbresults() must be called for each result set...
$status = $MSSQL::DBlib::dbh->dbresults();
if($status != FAIL && $DatabaseFunctions::DatabaseError ne "1")
	{
		if($DebugThisAp eq "1")
			{
				print "<!-- SUCCESS: $SqlStatement returned with dbresults status = ($status). -->\n";
			}
		my %dataref = ("jason" => "baumbach");
		my $dataref = \%dataref;
		# If in debug mode, print information...
		if($DebugThisAp == 1)
			{
				print "<!-- SQL: $SqlStatement -->\n";
			}
		my $affiliate_tracking_id = "";
		# Prevent infinite loop...
		while ($MSSQL::DBlib::dbh->dbnextrow2($dataref, 1) != NO_MORE_ROWS) 
			{
				$affiliate_tracking_id	 = $$dataref{affiliate_tracking_id};
				$plan_unique_id			 = $$dataref{plan_unique_id};
				$transaction_amount		 = $$dataref{transaction_amount};

				if($DebugThisAp eq "1")
					{
						print "<!-- affiliate_tracking_id = ($affiliate_tracking_id) -->\n";
						print "<!-- plan_unique_id        = ($plan_unique_id) -->\n";
						print "<!-- transaction_amount    = ($transaction_amount) -->\n";
					}
			}
		
		# Process the successful completion of the transaction...
		&UtilityFunctions::Print_HTML_Top($ProgramName, $DebugUtilityFunctions, %Map);
		print "\n<!-- SUCCESS:  Received message for ($transaction_id) was successfully logged to the DB. -->\n";
			
		print "                        <TABLE border=\"0\" width=\"100%\" cellspacing=\"3\" cellpadding=\"3\">\n";
		# Approved...
		if($x_response_code eq "1")
			{
			# START - Affiliate tracking code
			# Only initiate Action Processing if this transaction is an Auth Capture or a bypass (checking)
			if(length($affiliate_tracking_id) > 10 and ($transaction_type eq "AUTH_CAPTURE" or $transaction_type eq "auth_capture" or $QueryStringHash{'x_type'} eq "BYPASS"))
				{
					print "<SCRIPT type=\"text/javascript\" src=\"$Map{'AFL_CGIBIN'}/Afl_ProcessAction.cgi?ckuid=$affiliate_tracking_id&pluid=$plan_unique_id&ta=$transaction_amount&test_sql=1&test_cgi=1\"></SCRIPT>\n";
				} 
			else
				{
					print "<!-- no afl action initiated for ckuid ($affiliate_tracking_id) -->\n";
				}
			# END - Affiliate tracking code

    		if($transaction_type eq "AUTH_CAPTURE" or $transaction_type eq "auth_capture")
    			{
    				# user_name / WHICH_CONNECTIONS...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT>, thank you for becomming a Premium member of the growing $Map{'WHICH_CONNECTIONS'} community.</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
			elsif($transaction_type eq "CREDIT" or $transaction_type eq "credit")
    			{
    				# user_name / Credit...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT> was successfully credited $Map{'CURRENCY_SYMBOL'}$amount</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
			elsif($transaction_type eq "VOID" or $transaction_type eq "void")
    			{
    				# user_name / Credit...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\">Successfully voided <FONT color=\"#FF0033\">$user_name</FONT> transaction of $Map{'CURRENCY_SYMBOL'}$amount</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
    		elsif($QueryStringHash{'x_type'} eq "BYPASS")
    			{
    				# user_name / WHICH_CONNECTIONS...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT>, thank you for becomming a promotional member of the growing $Map{'WHICH_CONNECTIONS'} community.</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
			else
			{
    				# user_name / Unknown...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT> -- approved but unknown transaction type ($transaction_type) to us</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
			}

				# x_response_code...
				print "\n<!-- x_response_code: ($x_response_code) -->\n";
				# x_response_reason_text...
				print "\n<!-- x_response_reason_text: ($x_response_reason_text) -->\n\n";
				
				# transaction_id...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Transaction ID:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> $transaction_id</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				if($QueryStringHash{'x_type'} eq "BYPASS")
					{
						# months_joined / amount...
						print "                          <TR valign=\"middle\">\n";
						print "                            <TD height=\"30\" width=\"32%\">\n";
						print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Membership Type:</FONT></STRONG>\n";
						print "                            </TD>\n";
						print "                            <TD height=\"30\" width=\"13%\">\n";
						print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">$QueryStringHash{'membership_type_name'}</FONT>\n";
						print "                            </TD>\n";
						print "                          </TR>\n";
						print "                          <TR valign=\"middle\">\n";
						print "                            <TD height=\"30\" width=\"32%\">\n";
						print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Date Promotion Ends:</FONT></STRONG>\n";
						print "                            </TD>\n";
						print "                            <TD height=\"30\" width=\"13%\">\n";
						print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">$QueryStringHash{'x_ship_to_company'}</FONT>\n";
						print "                            </TD>\n";
						print "                          </TR>\n";
					}
				else
					{
						# months_joined / amount...
						print "                          <TR valign=\"middle\">\n";
						print "                            <TD height=\"30\" width=\"32%\">\n";
						print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Membership Type:</FONT></STRONG>\n";
						print "                            </TD>\n";
						print "                            <TD height=\"30\" width=\"13%\">\n";
						print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">$months_joined Month</FONT>\n";
						print "                            </TD>\n";
						print "                            <TD height=\"30\" width=\"55%\">\n";
						print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Total: $Map{'CURRENCY_SYMBOL'}$amount</FONT>\n";
						print "                            </TD>\n";
						print "                          </TR>\n";
					}
			}
		# Declined...
		elsif($x_response_code eq "2")
			{
    		if($transaction_type eq "AUTH_CAPTURE" or $transaction_type eq "auth_capture")
    			{
    				# user_name / WHICH_CONNECTIONS...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT>, $Map{'WHICH_CONNECTIONS'} is sorry but your credit card has been declined.</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
			elsif($transaction_type eq "CREDIT" or $transaction_type eq "credit")
    			{
    				# user_name / Credit...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT> could not be credited $Map{'CURRENCY_SYMBOL'}$amount</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
    			}
			else
			{
    				# user_name / Unknown...
    				print "                          <TR>\n";
    				print "                            <TD height=\"30\" colspan=\"3\">\n";
    				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT> -- was not credited $Map{'CURRENCY_SYMBOL'}$amount and there was an unknown transaction type ($transaction_type) to us</FONT></STRONG></FONT>\n";
    				print "                            </TD>\n";
    				print "                          </TR>\n";
			}
				# x_response_reason_text...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Reason Declined:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"><FONT color=\"#FF0033\"> $x_response_reason_text</FONT></FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				# transaction_id...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Transaction ID:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> $transaction_id</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
			}
		# Error...
		elsif($x_response_code eq "3")
			{
				# user_name / WHICH_CONNECTIONS...
				print "                          <TR>\n";
				print "                            <TD height=\"30\" colspan=\"3\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\"><STRONG><FONT size=\"3\"><FONT color=\"#FF0033\">$user_name</FONT>, $Map{'WHICH_CONNECTIONS'} is sorry but there has been an error while processing your transaction.</FONT></STRONG></FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				# x_response_reason_text...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Error Message:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"><FONT color=\"#FF0033\"> $x_response_reason_text</FONT></FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				# transaction_id...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Transaction ID:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> $transaction_id</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
			}
		# Unknown...

		# x_cvv2_resp_code...
		print "\n<!-- x_cvv2_resp_code: ($x_cvv2_resp_code) -->\n";

		if($QueryStringHash{'x_type'} ne "BYPASS")
			{
				# name_on_card...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Cardholder's Name:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> $name_on_card</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				# card_type...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Card Type:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> $card_type</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
				# last_four...
				print "                          <TR valign=\"middle\">\n";
				print "                            <TD height=\"30\" width=\"32%\">\n";
				print "                              <STRONG><FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\">Account Number:</FONT></STRONG>\n";
				print "                            </TD>\n";
				print "                            <TD height=\"30\" colspan=\"2\">\n";
				print "                              <FONT face=\"Arial, Helvetica, sans-serif\" size=\"2\"> ************$last_four</FONT>\n";
				print "                            </TD>\n";
				print "                          </TR>\n";
			}
		print "                        </TABLE>\n";
		&UtilityFunctions::Print_HTML_Bottom($ProgramName, $DebugUtilityFunctions, %Map);
	}# END if($status != FAIL)
else
	{
		$status = $MSSQL::DBlib::dbh->dbcancel();
		&UtilityFunctions::Print_Framed_Error("ERROR: The system is currently unable to process the creditcard transaciton for \"$user_name\".  Please try again<BR>(Note: If you continue to experience this problem contact $Map{'EMAIL'}.)<BR>\n", $DebugUtilityFunctions, %Map);
	}


#End HTML...
print "</HTML>\n";
exit 0;

