PRINT 'Populating all lookup tables...'

SET NOCOUNT ON
PRINT 'Populating cook...'
INSERT INTO cook (choice, value) VALUES ('Prefer not to say'			, '0' )
INSERT INTO cook (choice, value) VALUES ('Yes'							, '1' )
INSERT INTO cook (choice, value) VALUES ('No'							, '2' )
INSERT INTO cook (choice, value) VALUES ('Maybe'						, '3' )
INSERT INTO cook (choice, value) VALUES ('I will probably never cook'	, '4' )

SET NOCOUNT ON
PRINT 'Populating country...'

INSERT INTO country (choice, value, iso_name) VALUES ('Other...'					,'0'	,'OT')
INSERT INTO country (choice, value, iso_name) VALUES ('Afghanistan'					,'1'	,'AF')
INSERT INTO country (choice, value, iso_name) VALUES ('Albania'						,'2'	,'AL')
INSERT INTO country (choice, value, iso_name) VALUES ('Algeria'						,'3'	,'DZ')
INSERT INTO country (choice, value, iso_name) VALUES ('American Samoa'				,'4'	,'AS')
INSERT INTO country (choice, value, iso_name) VALUES ('Andorra'						,'5'	,'AD')
INSERT INTO country (choice, value, iso_name) VALUES ('Angola'						,'6'	,'AO')
INSERT INTO country (choice, value, iso_name) VALUES ('Anguilla'					,'7'	,'AI')
INSERT INTO country (choice, value, iso_name) VALUES ('Antarctica'					,'8'	,'AQ')
INSERT INTO country (choice, value, iso_name) VALUES ('Antigua/Barbuda'				,'9'	,'AG')
INSERT INTO country (choice, value, iso_name) VALUES ('Argentina'					,'10'	,'AR')
INSERT INTO country (choice, value, iso_name) VALUES ('Armenia'						,'11'	,'AM')
INSERT INTO country (choice, value, iso_name) VALUES ('Aruba'						,'12'	,'AW')
INSERT INTO country (choice, value, iso_name) VALUES ('Australia'					,'13'	,'AU')
INSERT INTO country (choice, value, iso_name) VALUES ('Austria'						,'14'	,'AT')
INSERT INTO country (choice, value, iso_name) VALUES ('Azerbaijan'					,'15'	,'AZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Bahamas'						,'16'	,'BS')
INSERT INTO country (choice, value, iso_name) VALUES ('Bahrain'						,'17'	,'BH')
INSERT INTO country (choice, value, iso_name) VALUES ('Bangladesh'					,'18'	,'BD')
INSERT INTO country (choice, value, iso_name) VALUES ('Barbados'					,'19'	,'BB')
INSERT INTO country (choice, value, iso_name) VALUES ('Belarus'						,'20'	,'BY')
INSERT INTO country (choice, value, iso_name) VALUES ('Belgium'						,'21'	,'BE')
INSERT INTO country (choice, value, iso_name) VALUES ('Belize'						,'22'	,'BZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Benin'						,'23'	,'BJ')
INSERT INTO country (choice, value, iso_name) VALUES ('Bermuda'						,'24'	,'BM')
INSERT INTO country (choice, value, iso_name) VALUES ('Bhutan'						,'25'	,'BT')
INSERT INTO country (choice, value, iso_name) VALUES ('Bolivia'						,'26'	,'BO')
INSERT INTO country (choice, value, iso_name) VALUES ('Bosnia-Herzegovina'			,'27'	,'BA')
INSERT INTO country (choice, value, iso_name) VALUES ('Botswana'					,'28'	,'BW')
INSERT INTO country (choice, value, iso_name) VALUES ('Bouvet Island'				,'29'	,'BV')
INSERT INTO country (choice, value, iso_name) VALUES ('Brazil'						,'30'	,'BR')
INSERT INTO country (choice, value, iso_name) VALUES ('British Indian Ocean T.'		,'31'	,'IO')
INSERT INTO country (choice, value, iso_name) VALUES ('Brunei Darussalam'			,'32'	,'BN')
INSERT INTO country (choice, value, iso_name) VALUES ('Bulgaria'					,'33'	,'BG')
INSERT INTO country (choice, value, iso_name) VALUES ('Burkina Faso'				,'34'	,'BF')
INSERT INTO country (choice, value, iso_name) VALUES ('Burundi'						,'35'	,'BI')
INSERT INTO country (choice, value, iso_name) VALUES ('Cambodia'					,'36'	,'KH')
INSERT INTO country (choice, value, iso_name) VALUES ('Cameroon'					,'37'	,'CM')
INSERT INTO country (choice, value, iso_name) VALUES ('Canada'						,'38'	,'CA')
INSERT INTO country (choice, value, iso_name) VALUES ('Cape Verde'					,'39'	,'CP')
INSERT INTO country (choice, value, iso_name) VALUES ('Cayman Islands'				,'40'	,'KY')
INSERT INTO country (choice, value, iso_name) VALUES ('Central African, Rep.'		,'41'	,'CF')
INSERT INTO country (choice, value, iso_name) VALUES ('Chad'						,'42'	,'TD')
INSERT INTO country (choice, value, iso_name) VALUES ('Chile'						,'43'	,'CH')
INSERT INTO country (choice, value, iso_name) VALUES ('China'						,'44'	,'CN')
INSERT INTO country (choice, value, iso_name) VALUES ('Christmas Island'			,'45'	,'CX')
INSERT INTO country (choice, value, iso_name) VALUES ('Cocoa (Keeling) Islands'		,'46'	,'CC')
INSERT INTO country (choice, value, iso_name) VALUES ('Colombia'					,'47'	,'CO')
INSERT INTO country (choice, value, iso_name) VALUES ('Comoros'						,'48'	,'KM')
INSERT INTO country (choice, value, iso_name) VALUES ('Congo'						,'49'	,'CG')
INSERT INTO country (choice, value, iso_name) VALUES ('Cook Islands'				,'50'	,'CK')
INSERT INTO country (choice, value, iso_name) VALUES ('Costa Rica'					,'51'	,'CR')
INSERT INTO country (choice, value, iso_name) VALUES ('Cote Divoire'				,'52'	,'CI')
INSERT INTO country (choice, value, iso_name) VALUES ('Croatia'						,'53'	,'HR')
INSERT INTO country (choice, value, iso_name) VALUES ('Cuba'						,'54'	,'CU')
INSERT INTO country (choice, value, iso_name) VALUES ('Cyprus'						,'55'	,'CY')
INSERT INTO country (choice, value, iso_name) VALUES ('Czech Republic'				,'56'	,'CZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Denmark'						,'57'	,'DK')
INSERT INTO country (choice, value, iso_name) VALUES ('Djibouti'					,'58'	,'DI')
INSERT INTO country (choice, value, iso_name) VALUES ('Dominica'					,'59'	,'DM')
INSERT INTO country (choice, value, iso_name) VALUES ('Dominican Republic'			,'60'	,'DO')
INSERT INTO country (choice, value, iso_name) VALUES ('East Timor'					,'61'	,'TP')
INSERT INTO country (choice, value, iso_name) VALUES ('Ecuador'						,'62'	,'EC')
INSERT INTO country (choice, value, iso_name) VALUES ('Egypt'						,'63'	,'EG')
INSERT INTO country (choice, value, iso_name) VALUES ('El Salvador'					,'64'	,'SV')
INSERT INTO country (choice, value, iso_name) VALUES ('Equatorial Guinea'			,'65'	,'GQ')
INSERT INTO country (choice, value, iso_name) VALUES ('Eritrea'						,'66'	,'ER')
INSERT INTO country (choice, value, iso_name) VALUES ('Estonia'						,'67'	,'EE')
INSERT INTO country (choice, value, iso_name) VALUES ('Ethiopia'					,'68'	,'ET')
INSERT INTO country (choice, value, iso_name) VALUES ('Falkland Islands-Malvinas'	,'69'	,'FK')
INSERT INTO country (choice, value, iso_name) VALUES ('Faroe Islands'				,'70'	,'FO')
INSERT INTO country (choice, value, iso_name) VALUES ('Fiji'						,'71'	,'FJ')
INSERT INTO country (choice, value, iso_name) VALUES ('Finland'						,'72'	,'FI')
INSERT INTO country (choice, value, iso_name) VALUES ('France'						,'73'	,'FR')
INSERT INTO country (choice, value, iso_name) VALUES ('French Guiana'				,'74'	,'GF')
INSERT INTO country (choice, value, iso_name) VALUES ('French Polynesia'			,'75'	,'PF')
INSERT INTO country (choice, value, iso_name) VALUES ('French Southern Ter.'		,'76'	,'TF')
INSERT INTO country (choice, value, iso_name) VALUES ('Gabon'						,'77'	,'GA')
INSERT INTO country (choice, value, iso_name) VALUES ('Gambia'						,'78'	,'GM')
INSERT INTO country (choice, value, iso_name) VALUES ('Georgia'						,'79'	,'GE')
INSERT INTO country (choice, value, iso_name) VALUES ('Germany'						,'80'	,'DE')
INSERT INTO country (choice, value, iso_name) VALUES ('Ghana'						,'81'	,'GH')
INSERT INTO country (choice, value, iso_name) VALUES ('Gibraltar'					,'82'	,'GI')
INSERT INTO country (choice, value, iso_name) VALUES ('Great Britain'				,'83'	,'UK')
INSERT INTO country (choice, value, iso_name) VALUES ('Greece'						,'84'	,'GR')
INSERT INTO country (choice, value, iso_name) VALUES ('Greenland'					,'85'	,'GL')
INSERT INTO country (choice, value, iso_name) VALUES ('Grenada'						,'86'	,'GD')
INSERT INTO country (choice, value, iso_name) VALUES ('Guadeloupe'					,'87'	,'GP')
INSERT INTO country (choice, value, iso_name) VALUES ('Guam'						,'88'	,'GU')
INSERT INTO country (choice, value, iso_name) VALUES ('Guatemala'					,'89'	,'GT')
INSERT INTO country (choice, value, iso_name) VALUES ('Guinea'						,'90'	,'GN')
INSERT INTO country (choice, value, iso_name) VALUES ('Guinea-Bissau'				,'91'	,'GW')
INSERT INTO country (choice, value, iso_name) VALUES ('Guyana'						,'92'	,'GU')
INSERT INTO country (choice, value, iso_name) VALUES ('Haiti'						,'93'	,'HT')
INSERT INTO country (choice, value, iso_name) VALUES ('Heard/Mc Donald Islands'		,'94'	,'HM')
INSERT INTO country (choice, value, iso_name) VALUES ('Honduras'					,'95'	,'HN')
INSERT INTO country (choice, value, iso_name) VALUES ('Hong Kong'					,'96'	,'HK')
INSERT INTO country (choice, value, iso_name) VALUES ('Hungary'						,'97'	,'HU')
INSERT INTO country (choice, value, iso_name) VALUES ('Iceland'						,'98'	,'IS')
INSERT INTO country (choice, value, iso_name) VALUES ('India'						,'99'	,'IN')
INSERT INTO country (choice, value, iso_name) VALUES ('Indonesia'					,'100'	,'ID')
INSERT INTO country (choice, value, iso_name) VALUES ('Iran'						,'101'	,'IR')
INSERT INTO country (choice, value, iso_name) VALUES ('Iraq'						,'102'	,'IQ')
INSERT INTO country (choice, value, iso_name) VALUES ('Ireland'						,'103'	,'IE')
INSERT INTO country (choice, value, iso_name) VALUES ('Israel'						,'104'	,'IL')
INSERT INTO country (choice, value, iso_name) VALUES ('Italy'						,'105'	,'IT')
INSERT INTO country (choice, value, iso_name) VALUES ('Jamaica'						,'106'	,'JM')
INSERT INTO country (choice, value, iso_name) VALUES ('Japan'						,'107'	,'JP')
INSERT INTO country (choice, value, iso_name) VALUES ('Jordan'						,'108'	,'JO')
INSERT INTO country (choice, value, iso_name) VALUES ('Kazakhstan'					,'109'	,'KZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Kenya'						,'110'	,'KE')
INSERT INTO country (choice, value, iso_name) VALUES ('Kiribati'					,'111'	,'KI')
INSERT INTO country (choice, value, iso_name) VALUES ('Korea, Democratic P. Rep.'	,'112'	,'KP')
INSERT INTO country (choice, value, iso_name) VALUES ('Korea, Republic'				,'113'	,'KR')
INSERT INTO country (choice, value, iso_name) VALUES ('Kuwait'						,'114'	,'KW')
INSERT INTO country (choice, value, iso_name) VALUES ('Kyrgyzstan'					,'115'	,'KG')
INSERT INTO country (choice, value, iso_name) VALUES ('Lao P. Democratic Rep.'		,'116'	,'LA')
INSERT INTO country (choice, value, iso_name) VALUES ('Latvia'						,'117'	,'LV')
INSERT INTO country (choice, value, iso_name) VALUES ('Lebanon'						,'118'	,'LB')
INSERT INTO country (choice, value, iso_name) VALUES ('Lesotho'						,'119'	,'LS')
INSERT INTO country (choice, value, iso_name) VALUES ('Liberia'						,'120'	,'LR')
INSERT INTO country (choice, value, iso_name) VALUES ('Libyan Arab Jamahiriya'		,'121'	,'LY')
INSERT INTO country (choice, value, iso_name) VALUES ('Liechtenstein'				,'122'	,'LI')
INSERT INTO country (choice, value, iso_name) VALUES ('Lithuania'					,'123'	,'LT')
INSERT INTO country (choice, value, iso_name) VALUES ('Luxembourg'					,'124'	,'LU')
INSERT INTO country (choice, value, iso_name) VALUES ('Macau'						,'125'	,'MO')
INSERT INTO country (choice, value, iso_name) VALUES ('Macedonia'					,'126'	,'MK')
INSERT INTO country (choice, value, iso_name) VALUES ('Madagascar'					,'127'	,'MG')
INSERT INTO country (choice, value, iso_name) VALUES ('Malawi'						,'128'	,'MW')
INSERT INTO country (choice, value, iso_name) VALUES ('Malaysia'					,'129'	,'MY')
INSERT INTO country (choice, value, iso_name) VALUES ('Maldives'					,'130'	,'MV')
INSERT INTO country (choice, value, iso_name) VALUES ('Mali'						,'131'	,'ML')
INSERT INTO country (choice, value, iso_name) VALUES ('Malta'						,'132'	,'MT')
INSERT INTO country (choice, value, iso_name) VALUES ('Marshall Islands'			,'133'	,'MH')
INSERT INTO country (choice, value, iso_name) VALUES ('Martinique'					,'134'	,'MQ')
INSERT INTO country (choice, value, iso_name) VALUES ('Mauritania'					,'135'	,'MU')
INSERT INTO country (choice, value, iso_name) VALUES ('Mauritius'					,'136'	,'MV')
INSERT INTO country (choice, value, iso_name) VALUES ('Mayotte'						,'137'	,'YT')
INSERT INTO country (choice, value, iso_name) VALUES ('Mexico'						,'138'	,'MX')
INSERT INTO country (choice, value, iso_name) VALUES ('Micronesia'					,'139'	,'FM')
INSERT INTO country (choice, value, iso_name) VALUES ('Moldova'						,'140'	,'MD')
INSERT INTO country (choice, value, iso_name) VALUES ('Monaco'						,'141'	,'MC')
INSERT INTO country (choice, value, iso_name) VALUES ('Mongolia'					,'142'	,'MN')
INSERT INTO country (choice, value, iso_name) VALUES ('Montserrat'					,'143'	,'MS')
INSERT INTO country (choice, value, iso_name) VALUES ('Morocco'						,'144'	,'MA')
INSERT INTO country (choice, value, iso_name) VALUES ('Mozambique'					,'145'	,'MZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Myanmar'						,'146'	,'MM')
INSERT INTO country (choice, value, iso_name) VALUES ('Namibia'						,'147'	,'NA')
INSERT INTO country (choice, value, iso_name) VALUES ('Nauru'						,'148'	,'NR')
INSERT INTO country (choice, value, iso_name) VALUES ('Nepal'						,'149'	,'NP')
INSERT INTO country (choice, value, iso_name) VALUES ('Netherlands'					,'150'	,'NL')
INSERT INTO country (choice, value, iso_name) VALUES ('Netherlands Antilles'		,'151'	,'AN')
INSERT INTO country (choice, value, iso_name) VALUES ('New Caledonia'				,'152'	,'NC')
INSERT INTO country (choice, value, iso_name) VALUES ('New Zealand'					,'153'	,'NZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Newfoundland'				,'154'	,'NF')
INSERT INTO country (choice, value, iso_name) VALUES ('Nicaragua'					,'155'	,'NI')
INSERT INTO country (choice, value, iso_name) VALUES ('Niger'						,'156'	,'NE')
INSERT INTO country (choice, value, iso_name) VALUES ('Nigeria'						,'157'	,'NG')
INSERT INTO country (choice, value, iso_name) VALUES ('Niue'						,'158'	,'NU')
INSERT INTO country (choice, value, iso_name) VALUES ('Norfolk Island'				,'159'	,'NF')
INSERT INTO country (choice, value, iso_name) VALUES ('Northern Mariana Islands'	,'160'	,'MP')
INSERT INTO country (choice, value, iso_name) VALUES ('Norway'						,'161'	,'NO')
INSERT INTO country (choice, value, iso_name) VALUES ('Oman'						,'162'	,'OM')
INSERT INTO country (choice, value, iso_name) VALUES ('Pakistan'					,'163'	,'PK')
INSERT INTO country (choice, value, iso_name) VALUES ('Palau'						,'164'	,'PW')
INSERT INTO country (choice, value, iso_name) VALUES ('Panama'						,'165'	,'PA')
INSERT INTO country (choice, value, iso_name) VALUES ('Papua New Guinea'			,'166'	,'PG')
INSERT INTO country (choice, value, iso_name) VALUES ('Paraguay'					,'167'	,'PY')
INSERT INTO country (choice, value, iso_name) VALUES ('Peru'						,'168'	,'PE')
INSERT INTO country (choice, value, iso_name) VALUES ('Philippines'					,'169'	,'PH')
INSERT INTO country (choice, value, iso_name) VALUES ('Pitcairn'					,'170'	,'PN')
INSERT INTO country (choice, value, iso_name) VALUES ('Poland'						,'171'	,'PL')
INSERT INTO country (choice, value, iso_name) VALUES ('Portugal'					,'172'	,'PT')
INSERT INTO country (choice, value, iso_name) VALUES ('Puerto Rico'					,'173'	,'PR')
INSERT INTO country (choice, value, iso_name) VALUES ('Qatar'						,'174'	,'QA')
INSERT INTO country (choice, value, iso_name) VALUES ('Reunion'						,'175'	,'RE')
INSERT INTO country (choice, value, iso_name) VALUES ('Romania'						,'176'	,'RO')
INSERT INTO country (choice, value, iso_name) VALUES ('Russia'						,'177'	,'RU')
INSERT INTO country (choice, value, iso_name) VALUES ('Rwanda'						,'178'	,'RW')
INSERT INTO country (choice, value, iso_name) VALUES ('S. Georgia/S. Sandwich I.'	,'179'	,'GS')
INSERT INTO country (choice, value, iso_name) VALUES ('Saint Kitts and Nevis'		,'180'	,'KN')
INSERT INTO country (choice, value, iso_name) VALUES ('Saint Lucia'					,'181'	,'LC')
INSERT INTO country (choice, value, iso_name) VALUES ('Saint Vincent/Grenadines'	,'182'	,'VC')
INSERT INTO country (choice, value, iso_name) VALUES ('Samoa'						,'183'	,'WS')
INSERT INTO country (choice, value, iso_name) VALUES ('San Marino'					,'184'	,'SM')
INSERT INTO country (choice, value, iso_name) VALUES ('Sao Tome and Principe'		,'185'	,'ST')
INSERT INTO country (choice, value, iso_name) VALUES ('Saudi Arabia'				,'186'	,'SA')
INSERT INTO country (choice, value, iso_name) VALUES ('Senegal'						,'187'	,'SE')
INSERT INTO country (choice, value, iso_name) VALUES ('Seychelles'					,'188'	,'SC')
INSERT INTO country (choice, value, iso_name) VALUES ('Sierra Leone'				,'189'	,'SL')
INSERT INTO country (choice, value, iso_name) VALUES ('Singapore'					,'190'	,'SG')
INSERT INTO country (choice, value, iso_name) VALUES ('Slovakia (Slovak Rep.)'		,'191'	,'SK')
INSERT INTO country (choice, value, iso_name) VALUES ('Slovenia'					,'192'	,'SI')
INSERT INTO country (choice, value, iso_name) VALUES ('Solomon Islands'				,'193'	,'SB')
INSERT INTO country (choice, value, iso_name) VALUES ('Somalia'						,'194'	,'SO')
INSERT INTO country (choice, value, iso_name) VALUES ('South Africa'				,'195'	,'ZA')
INSERT INTO country (choice, value, iso_name) VALUES ('Spain'						,'196'	,'ES')
INSERT INTO country (choice, value, iso_name) VALUES ('Sri Lanka'					,'197'	,'LK')
INSERT INTO country (choice, value, iso_name) VALUES ('St. Helena'					,'198'	,'SH')
INSERT INTO country (choice, value, iso_name) VALUES ('St. Pierre and Miquelon'		,'199'	,'PM')
INSERT INTO country (choice, value, iso_name) VALUES ('Sudan'						,'200'	,'SD')
INSERT INTO country (choice, value, iso_name) VALUES ('Suriname'					,'201'	,'SR')
INSERT INTO country (choice, value, iso_name) VALUES ('Svalbard/Jan Mayen Isl.'		,'202'	,'SJ')
INSERT INTO country (choice, value, iso_name) VALUES ('Swaziland'					,'203'	,'SZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Sweden'						,'204'	,'SE')
INSERT INTO country (choice, value, iso_name) VALUES ('Switzerland'					,'205'	,'CH')
INSERT INTO country (choice, value, iso_name) VALUES ('Syrian Arab Republic'		,'206'	,'SY')
INSERT INTO country (choice, value, iso_name) VALUES ('Taiwan'						,'207'	,'TW')
INSERT INTO country (choice, value, iso_name) VALUES ('Tajikistan'					,'208'	,'TJ')
INSERT INTO country (choice, value, iso_name) VALUES ('Tanzania'					,'209'	,'TZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Thailand'					,'210'	,'TH')
INSERT INTO country (choice, value, iso_name) VALUES ('Togo'						,'211'	,'TG')
INSERT INTO country (choice, value, iso_name) VALUES ('Tokelau'						,'212'	,'TK')
INSERT INTO country (choice, value, iso_name) VALUES ('Tonga'						,'213'	,'TO')
INSERT INTO country (choice, value, iso_name) VALUES ('Trinidad and Tobago'			,'214'	,'TT')
INSERT INTO country (choice, value, iso_name) VALUES ('Tunisia'						,'215'	,'TN')
INSERT INTO country (choice, value, iso_name) VALUES ('Turkey'						,'216'	,'TR')
INSERT INTO country (choice, value, iso_name) VALUES ('Turkmenistan'				,'217'	,'TM')
INSERT INTO country (choice, value, iso_name) VALUES ('Turks/Caicos Islands'		,'218'	,'TC')
INSERT INTO country (choice, value, iso_name) VALUES ('Tuvalu'						,'219'	,'TU')
INSERT INTO country (choice, value, iso_name) VALUES ('Uganda'						,'220'	,'UG')
INSERT INTO country (choice, value, iso_name) VALUES ('Ukraine'						,'221'	,'UA')
INSERT INTO country (choice, value, iso_name) VALUES ('United Arab Emirates'		,'222'	,'AE')
INSERT INTO country (choice, value, iso_name) VALUES ('United States'				,'223'	,'US')
INSERT INTO country (choice, value, iso_name) VALUES ('Uruguay'						,'224'	,'UY')
INSERT INTO country (choice, value, iso_name) VALUES ('US Minor Outlying Islands'	,'225'	,'UM')
INSERT INTO country (choice, value, iso_name) VALUES ('Uzbekistan'					,'226'	,'UZ')
INSERT INTO country (choice, value, iso_name) VALUES ('Vanuatu'						,'227'	,'VU')
INSERT INTO country (choice, value, iso_name) VALUES ('Vatican City'				,'228'	,'VA')
INSERT INTO country (choice, value, iso_name) VALUES ('Venezuela'					,'229'	,'VE')
INSERT INTO country (choice, value, iso_name) VALUES ('Viet Nam'					,'230'	,'VN')
INSERT INTO country (choice, value, iso_name) VALUES ('Virgin Islands (British)'	,'231'	,'VG')
INSERT INTO country (choice, value, iso_name) VALUES ('Virgin Islands (U.S.)'		,'232'	,'VI')
INSERT INTO country (choice, value, iso_name) VALUES ('Wallisw/Futuna Islands'		,'233'	,'WF')
INSERT INTO country (choice, value, iso_name) VALUES ('Western Sahara'				,'234'	,'EH')
INSERT INTO country (choice, value, iso_name) VALUES ('Yeman'						,'235'	,'YE')
INSERT INTO country (choice, value, iso_name) VALUES ('Yugoslavia'					,'236'	,'YU')
INSERT INTO country (choice, value, iso_name) VALUES ('Zaire'						,'237'	,'ZR')
INSERT INTO country (choice, value, iso_name) VALUES ('Zambia'						,'238'	,'ZM')
INSERT INTO country (choice, value, iso_name) VALUES ('Zimbabwe'					,'239'	,'ZW')

SET NOCOUNT ON
PRINT 'Populating credit_card_type...'
INSERT INTO credit_card_type (choice, value) VALUES ('American Express'	, '3')
INSERT INTO credit_card_type (choice, value) VALUES ('Visa'				, '4')
INSERT INTO credit_card_type (choice, value) VALUES ('Master Card'		, '5')
INSERT INTO credit_card_type (choice, value) VALUES ('Discover'			, '6')

SET NOCOUNT ON
PRINT 'Populating drink...'
INSERT INTO drink (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO drink (choice, value) VALUES ('Yes'					, '1')
INSERT INTO drink (choice, value) VALUES ('No'					, '2')
INSERT INTO drink (choice, value) VALUES ('Often'				, '3')
INSERT INTO drink (choice, value) VALUES ('Sometimes'			, '4')

SET NOCOUNT ON
PRINT 'Populating education...'
INSERT INTO education (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO education (choice, value) VALUES ('Still a student'		, '1')
INSERT INTO education (choice, value) VALUES ('High School'			, '2')
INSERT INTO education (choice, value) VALUES ('Some College'		, '3')
INSERT INTO education (choice, value) VALUES ('College Degree'		, '4')
INSERT INTO education (choice, value) VALUES ('Graduate Degree'		, '5')
INSERT INTO education (choice, value) VALUES ('Post Graduate'		, '6')

SET NOCOUNT ON
PRINT 'Populating eyes...'
INSERT INTO eyes (choice, value) VALUES ('Prefer not to say', '0')
INSERT INTO eyes (choice, value) VALUES ('Brown'			, '1')
INSERT INTO eyes (choice, value) VALUES ('Black'			, '2')
INSERT INTO eyes (choice, value) VALUES ('Blue'				, '3')
INSERT INTO eyes (choice, value) VALUES ('Green'			, '4')
INSERT INTO eyes (choice, value) VALUES ('Hazel'			, '5')

SET NOCOUNT ON
PRINT 'Populating hair...'
INSERT INTO hair (choice, value) VALUES ('Prefer not to say', '0')
INSERT INTO hair (choice, value) VALUES ('Black'			, '1')
INSERT INTO hair (choice, value) VALUES ('Brown'			, '2')
INSERT INTO hair (choice, value) VALUES ('Red'				, '3')
INSERT INTO hair (choice, value) VALUES ('Blonde'			, '4')
INSERT INTO hair (choice, value) VALUES ('Bald'				, '5')
INSERT INTO hair (choice, value) VALUES ('Other'			, '6')

SET NOCOUNT ON
PRINT 'Populating height...'
INSERT INTO height (choice, value) VALUES ('Prefer not to say'	,'0')
INSERT INTO height (choice, value) VALUES ('4\'' 01" (1.24m)'	,'1')
INSERT INTO height (choice, value) VALUES ('4\'' 02" (1.27m)'	,'2')
INSERT INTO height (choice, value) VALUES ('4\'' 03" (1.30m)'	,'3')
INSERT INTO height (choice, value) VALUES ('4\'' 04" (1.32m)'	,'4')
INSERT INTO height (choice, value) VALUES ('4\'' 05" (1.35m)'	,'5')
INSERT INTO height (choice, value) VALUES ('4\'' 06" (1.37m)'	,'6')
INSERT INTO height (choice, value) VALUES ('4\'' 07" (1.40m)'	,'7')
INSERT INTO height (choice, value) VALUES ('4\'' 08" (1.42m)'	,'8')
INSERT INTO height (choice, value) VALUES ('4\'' 09" (1.45m)'	,'9')
INSERT INTO height (choice, value) VALUES ('4\'' 10" (1.47m)'	,'10')
INSERT INTO height (choice, value) VALUES ('4\'' 11" (1.50m)'	,'11')
INSERT INTO height (choice, value) VALUES ('5\'' 00" (1.52m)'	,'12')
INSERT INTO height (choice, value) VALUES ('5\'' 01" (1.55m)'	,'13')
INSERT INTO height (choice, value) VALUES ('5\'' 02" (1.57m)'	,'14')
INSERT INTO height (choice, value) VALUES ('5\'' 03" (1.60m)'	,'15')
INSERT INTO height (choice, value) VALUES ('5\'' 04" (1.63m)'	,'16')
INSERT INTO height (choice, value) VALUES ('5\'' 05" (1.65m)'	,'17')
INSERT INTO height (choice, value) VALUES ('5\'' 06" (1.68m)'	,'18')
INSERT INTO height (choice, value) VALUES ('5\'' 07" (1.70m)'	,'19')
INSERT INTO height (choice, value) VALUES ('5\'' 08" (1.73m)'	,'20')
INSERT INTO height (choice, value) VALUES ('5\'' 09" (1.75m)'	,'21')
INSERT INTO height (choice, value) VALUES ('5\'' 10" (1.78m)'	,'22')
INSERT INTO height (choice, value) VALUES ('5\'' 11" (1.80m)'	,'23')
INSERT INTO height (choice, value) VALUES ('6\'' 00" (1.83m)'	,'24')
INSERT INTO height (choice, value) VALUES ('6\'' 01" (1.85m)'	,'25')
INSERT INTO height (choice, value) VALUES ('6\'' 02" (1.88m)'	,'26')
INSERT INTO height (choice, value) VALUES ('6\'' 03" (1.90m)'	,'27')
INSERT INTO height (choice, value) VALUES ('6\'' 04" (1.93m)'	,'28')
INSERT INTO height (choice, value) VALUES ('6\'' 05" (1.96m)'	,'29')
INSERT INTO height (choice, value) VALUES ('6\'' 06" (1.98m)'	,'30')
INSERT INTO height (choice, value) VALUES ('6\'' 07" (2.01m)'	,'31')
INSERT INTO height (choice, value) VALUES ('6\'' 08" (2.03m)'	,'32')
INSERT INTO height (choice, value) VALUES ('6\'' 09" (2.06m)'	,'33')
INSERT INTO height (choice, value) VALUES ('6\'' 10" (2.08m)'	,'34')
INSERT INTO height (choice, value) VALUES ('6\'' 11" (2.11m)'	,'35')
INSERT INTO height (choice, value) VALUES ('7\'' 00" (2.13m)'	,'36')
INSERT INTO height (choice, value) VALUES ('7\'' 01" (2.16m)'	,'37')
INSERT INTO height (choice, value) VALUES ('7\'' 02" (2.18m)'	,'38')
INSERT INTO height (choice, value) VALUES ('7\'' 03" (2.21m)'	,'39')
INSERT INTO height (choice, value) VALUES ('7\'' 04" (2.24m)'	,'40')
INSERT INTO height (choice, value) VALUES ('7\'' 05" (2.26m)'	,'41')
INSERT INTO height (choice, value) VALUES ('7\'' 06" (2.29m)'	,'42')

SET NOCOUNT ON
PRINT 'Populating housing_status...'
INSERT INTO housing_status (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO housing_status (choice, value) VALUES ('Live alone'			, '1')
INSERT INTO housing_status (choice, value) VALUES ('Live with room mate', '2')
INSERT INTO housing_status (choice, value) VALUES ('Live with parents'	, '3')

SET NOCOUNT ON
PRINT 'Populating marital_status...'
INSERT INTO marital_status (choice, value) VALUES ('Prefer not to say'		, '0')
INSERT INTO marital_status (choice, value) VALUES ('Single'					, '1')
INSERT INTO marital_status (choice, value) VALUES ('Single with children'	, '2')
INSERT INTO marital_status (choice, value) VALUES ('Married'				, '3')
INSERT INTO marital_status (choice, value) VALUES ('Divorced'				, '4')
INSERT INTO marital_status (choice, value) VALUES ('Divorced with children'	, '5')
INSERT INTO marital_status (choice, value) VALUES ('Widowed'				, '6')
INSERT INTO marital_status (choice, value) VALUES ('Widowed with children'	, '7')

SET NOCOUNT ON
PRINT 'Populating membership_type...'
INSERT INTO membership_type (membership_type_id, membership_type_name, date_promotion_started, date_promotion_ended, allow_search_simple, allow_search_advanced, allow_view_profiles, allow_mail_receive, allow_mail_read, allow_mail_send, allow_mail_reply, allow_romance_wizard, allow_chat_view, allow_chat_use, allow_view_stats) VALUES ('0', 'Guest'			,NULL					,NULL					, '1', '0', '0', '1', '1', '0', '1', '1', '2', '2', '2')
INSERT INTO membership_type (membership_type_id, membership_type_name, date_promotion_started, date_promotion_ended, allow_search_simple, allow_search_advanced, allow_view_profiles, allow_mail_receive, allow_mail_read, allow_mail_send, allow_mail_reply, allow_romance_wizard, allow_chat_view, allow_chat_use, allow_view_stats) VALUES ('1', 'Gold'			,NULL					,NULL					, '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2')
INSERT INTO membership_type (membership_type_id, membership_type_name, date_promotion_started, date_promotion_ended, allow_search_simple, allow_search_advanced, allow_view_profiles, allow_mail_receive, allow_mail_read, allow_mail_send, allow_mail_reply, allow_romance_wizard, allow_chat_view, allow_chat_use, allow_view_stats) VALUES ('2', 'Platinum'		,NULL					,NULL					, '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2')
INSERT INTO membership_type (membership_type_id, membership_type_name, date_promotion_started, date_promotion_ended, allow_search_simple, allow_search_advanced, allow_view_profiles, allow_mail_receive, allow_mail_read, allow_mail_send, allow_mail_reply, allow_romance_wizard, allow_chat_view, allow_chat_use, allow_view_stats) VALUES ('3', 'Promotion 1'	,'2001-11-25 00:00:00'	, '2001-11-30 00:00:00'	, '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2')
INSERT INTO membership_type (membership_type_id, membership_type_name, date_promotion_started, date_promotion_ended, allow_search_simple, allow_search_advanced, allow_view_profiles, allow_mail_receive, allow_mail_read, allow_mail_send, allow_mail_reply, allow_romance_wizard, allow_chat_view, allow_chat_use, allow_view_stats) VALUES ('4', 'International'	,'2001-11-30 00:00:00'	, '2001-12-15 00:00:00'	, '1', '1', '1', '1', '1', '1', '1', '1', '2', '2', '2')

SET NOCOUNT ON
PRINT 'Populating party...'
INSERT INTO party (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO party (choice, value) VALUES ('Never'				, '1')
INSERT INTO party (choice, value) VALUES ('Seldon'				, '2')
INSERT INTO party (choice, value) VALUES ('On the weekends'		, '3')
INSERT INTO party (choice, value) VALUES ('Every chance I get'	, '4')

SET NOCOUNT ON
PRINT 'Populating political...'
INSERT INTO political (choice, value) VALUES ('Prefer not to say'		, '0')
INSERT INTO political (choice, value) VALUES ('Liveral'					, '1')
INSERT INTO political (choice, value) VALUES ('Moderate Liberal'		, '2')
INSERT INTO political (choice, value) VALUES ('Moderate'				, '3')
INSERT INTO political (choice, value) VALUES ('Moderate Conservative'	, '4')
INSERT INTO political (choice, value) VALUES ('Conservative'			, '5')
INSERT INTO political (choice, value) VALUES ('Extreme Conservative'	, '6')

SET NOCOUNT ON
PRINT 'Populating profession...'
INSERT INTO profession (choice, value) VALUES ('Please choose one'					,'0' )
INSERT INTO profession (choice, value) VALUES ('Accounting/Finance'					,'1' )
INSERT INTO profession (choice, value) VALUES ('Advertising/Media'					,'2' )
INSERT INTO profession (choice, value) VALUES ('Advertising/Public Relations'		,'3' )
INSERT INTO profession (choice, value) VALUES ('Advertising'						,'4' )
INSERT INTO profession (choice, value) VALUES ('Airline - Aerospace'				,'5' )
INSERT INTO profession (choice, value) VALUES ('Apparel - Textile'					,'6' )
INSERT INTO profession (choice, value) VALUES ('Architecture'						,'7' )
INSERT INTO profession (choice, value) VALUES ('Art - Photography - Journalism'		,'8' )
INSERT INTO profession (choice, value) VALUES ('Arts/Entertainment/Publishing'		,'9' )
INSERT INTO profession (choice, value) VALUES ('Automotive - Motor Vehicles - Parts','10')
INSERT INTO profession (choice, value) VALUES ('Banking - Financial Services'		,'11')
INSERT INTO profession (choice, value) VALUES ('Bio-Pharmaceutical'					,'12')
INSERT INTO profession (choice, value) VALUES ('Biotechnology'						,'13')
INSERT INTO profession (choice, value) VALUES ('Building Materials'					,'14')
INSERT INTO profession (choice, value) VALUES ('Carpentry - Contruction'			,'15')
INSERT INTO profession (choice, value) VALUES ('Charitable - Not for Profit'		,'16')
INSERT INTO profession (choice, value) VALUES ('Clerical/Administrative'			,'17')
INSERT INTO profession (choice, value) VALUES ('Clerical/Service Worker'			,'18')
INSERT INTO profession (choice, value) VALUES ('Composer/Producer/Tech'				,'19')
INSERT INTO profession (choice, value) VALUES ('Computer Hardware'					,'20')
INSERT INTO profession (choice, value) VALUES ('Computer Software'					,'21')
INSERT INTO profession (choice, value) VALUES ('Construction/Real Estate/Facilities','22')
INSERT INTO profession (choice, value) VALUES ('Consultant'							,'23')
INSERT INTO profession (choice, value) VALUES ('Consulting'							,'24')
INSERT INTO profession (choice, value) VALUES ('Doctor/Medical Prof'				,'25')
INSERT INTO profession (choice, value) VALUES ('Education - College'				,'26')
INSERT INTO profession (choice, value) VALUES ('Education/Training'					,'27')
INSERT INTO profession (choice, value) VALUES ('Employment - Recruiting'			,'28')
INSERT INTO profession (choice, value) VALUES ('Energy - Utilities - Gas - Elec'	,'29')
INSERT INTO profession (choice, value) VALUES ('Engineering/Architecture'			,'30')
INSERT INTO profession (choice, value) VALUES ('Entertainment - Radio - TV - Media'	,'31')
INSERT INTO profession (choice, value) VALUES ('Finance/Accounting'					,'32')
INSERT INTO profession (choice, value) VALUES ('Food Services'						,'33')
INSERT INTO profession (choice, value) VALUES ('Government - Civil Service'			,'34')
INSERT INTO profession (choice, value) VALUES ('Graphic Artist/Designer'			,'35')
INSERT INTO profession (choice, value) VALUES ('Health - Medical - Home Services'	,'36')
INSERT INTO profession (choice, value) VALUES ('Health Care'						,'37')
INSERT INTO profession (choice, value) VALUES ('Home Business'						,'38')
INSERT INTO profession (choice, value) VALUES ('Home Maker'							,'39')
INSERT INTO profession (choice, value) VALUES ('Hospitality'						,'40')
INSERT INTO profession (choice, value) VALUES ('Human Resources'					,'41')
INSERT INTO profession (choice, value) VALUES ('HVAC'								,'42')
INSERT INTO profession (choice, value) VALUES ('Industrial'							,'43')
INSERT INTO profession (choice, value) VALUES ('Insurance'							,'44')
INSERT INTO profession (choice, value) VALUES ('Internet'							,'45')
INSERT INTO profession (choice, value) VALUES ('K-12 Faculty/Staff'					,'46')
INSERT INTO profession (choice, value) VALUES ('Law Enforcement - Military'			,'47')
INSERT INTO profession (choice, value) VALUES ('Lawyer/Paralegal/Assistant'			,'48')
INSERT INTO profession (choice, value) VALUES ('Legal'								,'49')
INSERT INTO profession (choice, value) VALUES ('Manufacturing/Operations'			,'50')
INSERT INTO profession (choice, value) VALUES ('Manufacturing'						,'51')
INSERT INTO profession (choice, value) VALUES ('Marketing'							,'52')
INSERT INTO profession (choice, value) VALUES ('Merchandising'						,'53')
INSERT INTO profession (choice, value) VALUES ('Middle Management'					,'54')
INSERT INTO profession (choice, value) VALUES ('MIS/Programming'					,'55')
INSERT INTO profession (choice, value) VALUES ('Mortgage'							,'56')
INSERT INTO profession (choice, value) VALUES ('New Media/Internet'					,'57')
INSERT INTO profession (choice, value) VALUES ('Office Equipment'					,'58')
INSERT INTO profession (choice, value) VALUES ('Office Manager/Admin'				,'59')
INSERT INTO profession (choice, value) VALUES ('Oil Refining - Petroleum'			,'60')
INSERT INTO profession (choice, value) VALUES ('Pharmaceutical'						,'61')
INSERT INTO profession (choice, value) VALUES ('Political'							,'62')
INSERT INTO profession (choice, value) VALUES ('Prefer not to say'					,'63')
INSERT INTO profession (choice, value) VALUES ('Printing - Publishing'				,'64')
INSERT INTO profession (choice, value) VALUES ('Professional/Technical'				,'65')
INSERT INTO profession (choice, value) VALUES ('Public Relations - Fund Raising'	,'66')
INSERT INTO profession (choice, value) VALUES ('Public Sector'						,'67')
INSERT INTO profession (choice, value) VALUES ('R&D Engineering'					,'68')
INSERT INTO profession (choice, value) VALUES ('Real Estate - Property Mgt'			,'69')
INSERT INTO profession (choice, value) VALUES ('Recreation'							,'70')
INSERT INTO profession (choice, value) VALUES ('Retail'								,'71')
INSERT INTO profession (choice, value) VALUES ('Retail Products'					,'72')
INSERT INTO profession (choice, value) VALUES ('Retired'							,'73')
INSERT INTO profession (choice, value) VALUES ('Sales'								,'74')
INSERT INTO profession (choice, value) VALUES ('Sales/Marketing'					,'75')
INSERT INTO profession (choice, value) VALUES ('Scientist/Researcher'				,'76')
INSERT INTO profession (choice, value) VALUES ('Semiconductor - Electronics'		,'77')
INSERT INTO profession (choice, value) VALUES ('Technical Management'				,'78')
INSERT INTO profession (choice, value) VALUES ('Technology'							,'79')
INSERT INTO profession (choice, value) VALUES ('Telecommunications'					,'80')
INSERT INTO profession (choice, value) VALUES ('Telecommunications'					,'81')
INSERT INTO profession (choice, value) VALUES ('Tourism'							,'82')
INSERT INTO profession (choice, value) VALUES ('Tradesman'							,'83')
INSERT INTO profession (choice, value) VALUES ('Training'							,'84')
INSERT INTO profession (choice, value) VALUES ('Transportation - Railroad'			,'85')
INSERT INTO profession (choice, value) VALUES ('Transportation/Logistics'			,'86')
INSERT INTO profession (choice, value) VALUES ('University Staff'					,'87')
INSERT INTO profession (choice, value) VALUES ('University Student'					,'88')
INSERT INTO profession (choice, value) VALUES ('Upper Management/Executive'			,'89')

SET NOCOUNT ON
PRINT 'Populating income...'
INSERT INTO income (choice, value) VALUES ('Prefer not to say'		, '0')
INSERT INTO income (choice, value) VALUES ('Less than $24,999'		, '1')
INSERT INTO income (choice, value) VALUES ('$25,000 to $34,999'		, '2')
INSERT INTO income (choice, value) VALUES ('$35,000 to $49,999'		, '3')
INSERT INTO income (choice, value) VALUES ('$50,000 to $74,999'		, '4')
INSERT INTO income (choice, value) VALUES ('$75,000 to $99,999'		, '5')
INSERT INTO income (choice, value) VALUES ('$100,000 to $149,999'	, '6')
INSERT INTO income (choice, value) VALUES ('$150,000+'				, '7')

SET NOCOUNT ON
PRINT 'Populating religion...'
INSERT INTO religion (choice, value) VALUES ('Prefer not to say', '0')
INSERT INTO religion (choice, value) VALUES ('Islam'			, '1')
INSERT INTO religion (choice, value) VALUES ('Christian'		, '2')
INSERT INTO religion (choice, value) VALUES ('Catholic'			, '3')
INSERT INTO religion (choice, value) VALUES ('Jewish'			, '4')
INSERT INTO religion (choice, value) VALUES ('Zoroastrian'		, '5')
INSERT INTO religion (choice, value) VALUES ('Bahai'			, '6')
INSERT INTO religion (choice, value) VALUES ('Other'			, '7')
INSERT INTO religion (choice, value) VALUES ('Not religious'	, '8')

SET NOCOUNT ON
PRINT 'Populating sex...'
INSERT INTO sex (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO sex (choice, value) VALUES ('Male'				, '1')
INSERT INTO sex (choice, value) VALUES ('Female'			, '2')

SET NOCOUNT ON
PRINT 'Populating sex_preference...'
INSERT INTO sex_preference (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO sex_preference (choice, value) VALUES ('Straight'			, '1')
INSERT INTO sex_preference (choice, value) VALUES ('Bi-Curious'			, '2')
INSERT INTO sex_preference (choice, value) VALUES ('Bi'					, '3')
INSERT INTO sex_preference (choice, value) VALUES ('Gay/Lesbian'		, '4')

SET NOCOUNT ON
PRINT 'Populating smoke...'
INSERT INTO smoke (choice, value) VALUES ('Prefer not to say'	, '0')
INSERT INTO smoke (choice, value) VALUES ('Yes'					, '1')
INSERT INTO smoke (choice, value) VALUES ('No'					, '2')
INSERT INTO smoke (choice, value) VALUES ('Sometimes'			, '3')

SET NOCOUNT ON
PRINT 'Populating state...'
INSERT INTO state (choice, value, iso_name) VALUES ('Prefer not to say'	,'0' ,'OT')
INSERT INTO state (choice, value, iso_name) VALUES ('Alabama'			,'1' ,'AL')
INSERT INTO state (choice, value, iso_name) VALUES ('Alaska'			,'2' ,'AK')
INSERT INTO state (choice, value, iso_name) VALUES ('Arizona'			,'3' ,'AZ')
INSERT INTO state (choice, value, iso_name) VALUES ('Arkansas'			,'4' ,'AR')
INSERT INTO state (choice, value, iso_name) VALUES ('California'		,'5' ,'CA')
INSERT INTO state (choice, value, iso_name) VALUES ('Colorado'			,'9' ,'CO')
INSERT INTO state (choice, value, iso_name) VALUES ('Connecticut'		,'10','CT')
INSERT INTO state (choice, value, iso_name) VALUES ('Delaware'			,'11','DE')
INSERT INTO state (choice, value, iso_name) VALUES ('Washington, D.C.'	,'12','DC')
INSERT INTO state (choice, value, iso_name) VALUES ('Florida'			,'13','FL')
INSERT INTO state (choice, value, iso_name) VALUES ('Georgia'			,'14','GA')
INSERT INTO state (choice, value, iso_name) VALUES ('Hawaii'			,'16','HI')
INSERT INTO state (choice, value, iso_name) VALUES ('Idaho'				,'17','ID')
INSERT INTO state (choice, value, iso_name) VALUES ('Illinois'			,'18','IL')
INSERT INTO state (choice, value, iso_name) VALUES ('Indiana'			,'19','IN')
INSERT INTO state (choice, value, iso_name) VALUES ('Iowa'				,'20','IA')
INSERT INTO state (choice, value, iso_name) VALUES ('Kansas'			,'21','KS')
INSERT INTO state (choice, value, iso_name) VALUES ('Kentucky'			,'22','KY')
INSERT INTO state (choice, value, iso_name) VALUES ('Louisiana'			,'23','LA')
INSERT INTO state (choice, value, iso_name) VALUES ('Maine'				,'24','ME')
INSERT INTO state (choice, value, iso_name) VALUES ('Maryland'			,'25','MD')
INSERT INTO state (choice, value, iso_name) VALUES ('Massachusetts'		,'26','MA')
INSERT INTO state (choice, value, iso_name) VALUES ('Michigan'			,'27','MI')
INSERT INTO state (choice, value, iso_name) VALUES ('Minnesota'			,'28','MN')
INSERT INTO state (choice, value, iso_name) VALUES ('Mississippi'		,'29','MS')
INSERT INTO state (choice, value, iso_name) VALUES ('Missouri'			,'30','MO')
INSERT INTO state (choice, value, iso_name) VALUES ('Montana'			,'31','MT')
INSERT INTO state (choice, value, iso_name) VALUES ('Nebraska'			,'32','NE')
INSERT INTO state (choice, value, iso_name) VALUES ('Nevada'			,'33','NV')
INSERT INTO state (choice, value, iso_name) VALUES ('New Hampshire'		,'34','NH')
INSERT INTO state (choice, value, iso_name) VALUES ('New Jersey'		,'35','NJ')
INSERT INTO state (choice, value, iso_name) VALUES ('New Mexico'		,'36','NM')
INSERT INTO state (choice, value, iso_name) VALUES ('New York'			,'37','NY')
INSERT INTO state (choice, value, iso_name) VALUES ('North Carolina'	,'39','NC')
INSERT INTO state (choice, value, iso_name) VALUES ('North Dakota'		,'40','ND')
INSERT INTO state (choice, value, iso_name) VALUES ('Ohio'				,'41','OH')
INSERT INTO state (choice, value, iso_name) VALUES ('Oklahoma'			,'42','OK')
INSERT INTO state (choice, value, iso_name) VALUES ('Oregon'			,'43','OR')
INSERT INTO state (choice, value, iso_name) VALUES ('Pennsylvania'		,'44','PA')
INSERT INTO state (choice, value, iso_name) VALUES ('Rhode Island'		,'46','RI')
INSERT INTO state (choice, value, iso_name) VALUES ('South Carolina'	,'47','SC')
INSERT INTO state (choice, value, iso_name) VALUES ('South Dakota'		,'48','SD')
INSERT INTO state (choice, value, iso_name) VALUES ('Tennessee'			,'49','TN')
INSERT INTO state (choice, value, iso_name) VALUES ('Texas'				,'50','TX')
INSERT INTO state (choice, value, iso_name) VALUES ('Utah'				,'54','UT')
INSERT INTO state (choice, value, iso_name) VALUES ('Vermont'			,'55','VT')
INSERT INTO state (choice, value, iso_name) VALUES ('Virginia'			,'56','VA')
INSERT INTO state (choice, value, iso_name) VALUES ('Washington'		,'57','WA')
INSERT INTO state (choice, value, iso_name) VALUES ('West Virginia'		,'58','WV')
INSERT INTO state (choice, value, iso_name) VALUES ('Wisconsin'			,'59','WI')
INSERT INTO state (choice, value, iso_name) VALUES ('Wyoming'			,'60','WY')

SET NOCOUNT ON
PRINT 'Populating weight...'
INSERT INTO weight (choice, value) VALUES ('Prefer not to say'	,'0' )
INSERT INTO weight (choice, value) VALUES ('85 lbs.  (39kg)'	,'1' )
INSERT INTO weight (choice, value) VALUES ('90 lbs.  (41kg)'	,'2' )
INSERT INTO weight (choice, value) VALUES ('95 lbs.  (43kg)'	,'3' )
INSERT INTO weight (choice, value) VALUES ('100 lbs. (45kg)'	,'4' )
INSERT INTO weight (choice, value) VALUES ('105 lbs. (48kg)'	,'5' )
INSERT INTO weight (choice, value) VALUES ('110 lbs. (50kg)'	,'6' )
INSERT INTO weight (choice, value) VALUES ('115 lbs. (52kg)'	,'7' )
INSERT INTO weight (choice, value) VALUES ('120 lbs. (54kg)'	,'8' )
INSERT INTO weight (choice, value) VALUES ('125 lbs. (57kg)'	,'9' )
INSERT INTO weight (choice, value) VALUES ('130 lbs. (59kg)'	,'10')
INSERT INTO weight (choice, value) VALUES ('135 lbs. (61kg)'	,'11')
INSERT INTO weight (choice, value) VALUES ('140 lbs. (64kg)'	,'12')
INSERT INTO weight (choice, value) VALUES ('145 lbs. (66kg)'	,'13')
INSERT INTO weight (choice, value) VALUES ('150 lbs. (68kg)'	,'14')
INSERT INTO weight (choice, value) VALUES ('155 lbs. (70kg)'	,'15')
INSERT INTO weight (choice, value) VALUES ('160 lbs. (73kg)'	,'16')
INSERT INTO weight (choice, value) VALUES ('165 lbs. (75kg)'	,'17')
INSERT INTO weight (choice, value) VALUES ('170 lbs. (77kg)'	,'18')
INSERT INTO weight (choice, value) VALUES ('175 lbs. (79kg)'	,'19')
INSERT INTO weight (choice, value) VALUES ('180 lbs. (82kg)'	,'20')
INSERT INTO weight (choice, value) VALUES ('185 lbs. (84kg)'	,'21')
INSERT INTO weight (choice, value) VALUES ('190 lbs. (86kg)'	,'22')
INSERT INTO weight (choice, value) VALUES ('195 lbs. (88kg)'	,'23')
INSERT INTO weight (choice, value) VALUES ('200 lbs. (91kg)'	,'24')
INSERT INTO weight (choice, value) VALUES ('205 lbs. (93kg)'	,'25')
INSERT INTO weight (choice, value) VALUES ('210 lbs. (95kg)'	,'26')
INSERT INTO weight (choice, value) VALUES ('215 lbs. (98kg)'	,'27')
INSERT INTO weight (choice, value) VALUES ('220 lbs. (100kg)'	,'28')
INSERT INTO weight (choice, value) VALUES ('225 lbs. (102kg)'	,'29')
INSERT INTO weight (choice, value) VALUES ('230 lbs. (104kg)'	,'30')
INSERT INTO weight (choice, value) VALUES ('235 lbs. (107kg)'	,'31')
INSERT INTO weight (choice, value) VALUES ('240 lbs. (109kg)'	,'32')
INSERT INTO weight (choice, value) VALUES ('245 lbs. (111kg)'	,'33')
INSERT INTO weight (choice, value) VALUES ('250 lbs. (113kg)'	,'34')
INSERT INTO weight (choice, value) VALUES ('255 lbs. (116kg)'	,'35')
INSERT INTO weight (choice, value) VALUES ('260 lbs. (118kg)'	,'36')
INSERT INTO weight (choice, value) VALUES ('265 lbs. (120kg)'	,'37')
INSERT INTO weight (choice, value) VALUES ('270 lbs. (122kg)'	,'38')
INSERT INTO weight (choice, value) VALUES ('275 lbs. (125kg)'	,'39')
INSERT INTO weight (choice, value) VALUES ('280 lbs. (127kg)'	,'40')
INSERT INTO weight (choice, value) VALUES ('285 lbs. (129kg)'	,'41')
INSERT INTO weight (choice, value) VALUES ('290 lbs. (132kg)'	,'42')
INSERT INTO weight (choice, value) VALUES ('295 lbs. (134kg)'	,'43')
INSERT INTO weight (choice, value) VALUES ('300 lbs. (136kg)'	,'44')
INSERT INTO weight (choice, value) VALUES ('300+ lbs.(136kg+)'	,'45')
